### ISSUE TITLE
Unable to retrieve and update expenses from csv

### ISSUE THREAD

**Issue by KwanHW** [laughingkid-sg/OneBoard-backend#2] opened 2021-07-25 06:21 UTC
To test:
1. Upload CSV
2. Expenses uploaded by CSV reflects on transaction history
3. Refresh Expense Summary by changing either duration or period

Expected Output:
Metrics of newly uploaded CSV should be shown

Actual Output: 
Response retrieved does not have the expenses added in the CSV 

On deletion or edit, a 404 message is shown saying that such expense does not exist even though it exists in the database 

![image](https://user-images.githubusercontent.com/13163631/126889763-b29d4c5c-d8ef-4552-8d88-3f0636763c02.png)

**Comment by laughingkid-sg** [comment] 2021-07-25 07:16
The issue is caused by 2 problems

1. Collection index is not updating, thus unable to write to expenses collection. Resolved by dropping collection.
2. Missing code to link `expense._id` back to the user. This is resolved by updating the necessary code to add the new expenses to the `user` item

The problem is resolved.

**Closed as completed by laughingkid-sg** 2021-07-25 07:16 UTC
